service: aws-lamda-crud-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:216022134244:table/TaskTable

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  addTask:
    handler: src/addTask.run
    events: 
      - httpApi:
          path: /tasks
          method: post
  getTasks:
    handler: src/getTasks.run
    events: 
      - httpApi:
          path: /tasks
          method: get
  getTaskById:
    handler: src/getTaskById.run
    events:
      - httpApi:
          path: /tasks/{id}
          method: get
  updateTask: 
    handler: src/updateTask.run
    events:
      - httpApi:
          path: /tasks/{id}
          method: put
  deleteTask: 
    handler: src/deleteTask.run
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
